FROM docker.io/library/golang:1.18-alpine AS builder
WORKDIR /src
COPY go.mod .
COPY main.go .
RUN go mod tidy && CGO_ENABLED=0 GOOS=linux go build -o /app main.go

FROM registry.access.redhat.com/ubi9-minimal:latest
COPY --from=builder /app /usr/local/bin/app
ENTRYPOINT ["/usr/local/bin/app"]
